spring:
  mail:
    host: smtp.163.com
    username: 17715090315@163.com
    password: UDHEEXDSUIIAPTKL
    port: 25

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.97.14:3306/enterprise?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowMultiQueries=true&useOldAliasMetadataBehavior=true&autoReconnect=true&failOverReadOnly=false
    username: user
    password: Password123456

#mybatis:
#  mapper-locations: classpath:./mapper/*.xml


